services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password

  python:
    build: .
    volumes:
    - ./app:/app
    working_dir: /app
    depends_on:
    - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/postgres
